In [1]:
import scraper as s
import pandas as pd
import numpy as np
import datetime
m = s.stockMongo()

In [2]:
apple = m.get_options("AAPL")

In [3]:
apple

,ask,bid,contract,in-money,iv,last,last_trade,strike,strike-date,type,volume
date,,,,,,,,,,,
2020-08-02 23:39:37.026,332.30,327.95,AAPL200918C00095000,in-the-money,148.44%,284.24,2020-07-30,95.0,2020-09-18,Call,2.0
2020-08-02 23:39:37.026,279.25,277.65,AAPL200918C00100000,in-the-money,0.00%,254.30,2020-06-29,100.0,2020-09-18,Call,1.0
2020-08-02 23:39:37.026,322.50,318.00,AAPL200918C00105000,in-the-money,152.54%,264.25,2020-07-23,105.0,2020-09-18,Call,1.0
2020-08-02 23:39:37.026,317.30,312.90,AAPL200918C00110000,in-the-money,129.69%,266.25,2020-07-27,110.0,2020-09-18,Call,1.0
2020-08-02 23:39:37.026,258.90,254.10,AAPL200918C00115000,in-the-money,0.00%,255.30,2020-06-23,115.0,2020-09-18,Call,2.0
...,...,...,...,...,...,...,...,...,...,...,...
2020-09-10 20:02:41.636,6.25,5.20,AAPL220916P00700000,in-the-money,0.00%,22.20,2020-08-27,700.0,2022-09-16,Put,23.0
2020-09-10 20:02:41.636,6.65,5.60,AAPL220916P00720000,in-the-money,0.00%,6.00,2020-08-25,720.0,2022-09-16,Put,10.0
2020-09-10 20:02:41.636,7.10,6.45,AAPL220916P00740000,in-the-money,0.00%,26.80,2020-08-26,740.0,2022-09-16,Put,NaN
2020-09-10 20:02:41.636,429.50,425.50,AAPL220916P00900000,in-the-money,0.00%,424.83,2020-08-27,900.0,2022-09-16,Put,3.0
2020-09-10 20:02:41.636,523.00,519.00,AAPL220916P01000000,in-the-money,0.00%,521.65,2020-08-28,NaN,2022-09-16,Put,17.0

In [3]:
apple = apple.where(apple['last_trade']==apple.index.date).dropna()
#apple = apple['2020-08-10'].where(apple['2020-08-10']['strike-date']=='2021-09-16').dropna()

In [5]:
apple

,ask,bid,contract,in-money,iv,last,last_trade,strike,strike-date,type,volume
date,,,,,,,,,,,
2020-08-03 20:01:56.675,157.70,156.90,AAPL200814C00280000,in-the-money,141.72%,158.55,2020-08-03,280.0,2020-08-14,Call,4.0
2020-08-03 20:01:56.675,152.80,151.80,AAPL200814C00285000,in-the-money,136.87%,151.19,2020-08-03,285.0,2020-08-14,Call,5.0
2020-08-03 20:01:56.675,148.00,147.10,AAPL200814C00290000,in-the-money,136.08%,148.74,2020-08-03,290.0,2020-08-14,Call,1.0
2020-08-03 20:01:56.675,137.90,137.05,AAPL200814C00300000,in-the-money,125.44%,141.60,2020-08-03,300.0,2020-08-14,Call,15.0
2020-08-03 20:01:56.675,123.00,122.35,AAPL200814C00315000,in-the-money,114.28%,121.64,2020-08-03,315.0,2020-08-14,Call,2.0
...,...,...,...,...,...,...,...,...,...,...,...
2020-09-10 20:02:41.636,51.50,50.70,AAPL220916P00150000,in-the-money,40.69%,51.70,2020-09-10,150.0,2022-09-16,Put,3.0
2020-09-10 20:02:41.636,72.15,71.05,AAPL220916P00175000,in-the-money,41.07%,70.50,2020-09-10,175.0,2022-09-16,Put,4.0
2020-09-10 20:02:41.636,94.20,92.95,AAPL220916P00200000,in-the-money,41.44%,93.20,2020-09-10,200.0,2022-09-16,Put,2.0
2020-09-10 20:02:41.636,117.30,115.65,AAPL220916P00225000,in-the-money,42.10%,116.70,2020-09-10,225.0,2022-09-16,Put,11.0
2020-09-10 20:02:41.636,141.00,139.00,AAPL220916P00250000,in-the-money,42.82%,140.25,2020-09-10,250.0,2022-09-16,Put,12.0

In [30]:
#apl = m.stock_data.stock_price.find({'sym':'AAPL'})
#apl[1]['stockdata']['Previous Close']['0']
#cleanSymbols = []
#for s in apl:
#    print(s)
#    cleanSymbols.append([s['stockdata']['Previous Close']['0'], s['date']])
#op = pd.concat(cleanSymbols)

117.32

In [7]:
apl = m.get_stock_data('AAPL')
#apl['date'] = pd.to_datetime(apl.index, "%Y-%m-%d")
#a = m.stock_data.pricedata.find({'sym': 'AAPL'})

In [6]:
df = pd.DataFrame.from_records(a[0]['timeline'])
df

                            c         h         l         o         v
2020-01-02 00:00:00  298.8300  299.0800  293.6700  294.7199  33870100
2020-01-03 00:00:00  295.9247  299.0747  294.9947  295.6447  36580700
2020-01-06 00:00:00  298.2827  298.4427  291.2327  292.2727  29596800
2020-01-07 00:00:00  296.8799  299.3899  295.9699  298.3299  27218000
2020-01-08 00:00:00  301.6555  302.9055  295.6255  295.6255  33019800
...                       ...       ...       ...       ...       ...
2020-08-05 00:00:00  440.2500  441.5700  435.5900  437.5100  30444200
2020-08-06 00:00:00  455.6100  457.6500  439.5000  441.6200  49322586
2020-08-07 13:30:00  444.4500  454.7000  441.1700  452.8200  49453300
2020-08-10 13:30:00  450.9100  455.1000  440.0000  450.4000  53032600
2020-08-11 13:30:00  439.3750  449.8500  439.0000  447.8750  37323921

[154 rows x 5 columns]

In [8]:
apl
#apl.where(apl['date']=='2020-06-09').dropna()

                            c         h         l         o         v
2020-01-02 00:00:00  298.8300  299.0800  293.6700  294.7199  33870100
2020-01-03 00:00:00  295.9247  299.0747  294.9947  295.6447  36580700
2020-01-06 00:00:00  298.2827  298.4427  291.2327  292.2727  29596800
2020-01-07 00:00:00  296.8799  299.3899  295.9699  298.3299  27218000
2020-01-08 00:00:00  301.6555  302.9055  295.6255  295.6255  33019800
...                       ...       ...       ...       ...       ...
2020-08-05 00:00:00  440.2500  441.5700  435.5900  437.5100  30444200
2020-08-06 00:00:00  455.6100  457.6500  439.5000  441.6200  49322586
2020-08-07 13:30:00  444.4500  454.7000  441.1700  452.8200  49453300
2020-08-10 13:30:00  450.9100  455.1000  440.0000  450.4000  53032600
2020-08-11 13:30:00  439.3750  449.8500  439.0000  447.8750  37323921

[154 rows x 5 columns]

In [9]:
apple_calls = apple.where(apple['type']=="Call").dropna()
apple_puts = apple.where(apple['type']=="Put").dropna()
apple_calls

Empty DataFrame
Columns: [ask, bid, contract, in-money, iv, last, last_trade, strike, strike-date, type, volume]
Index: []

In [8]:
matrix = []
for i in range(len(apple_calls)-1):
    for j in range(len(apple_puts)-1):
        matrix.append([[apple_calls.iloc[i+1,2], apple_calls.iloc[i,2], apple_puts.iloc[j+1,2], apple_puts.iloc[j,2]],
                       apple_calls.iloc[i+1,7]-apple_calls.iloc[i,7]+apple_puts.iloc[j+1,7]-apple_puts.iloc[j,7],
                        apple_calls.iloc[i+1,5]-apple_calls.iloc[i,5]+apple_puts.iloc[j+1,5]-apple_puts.iloc[j,5],
                       [apple_calls.iloc[i+1,7],apple_calls.iloc[i,7],apple_puts.iloc[j+1,7],apple_puts.iloc[j,7]],
                      ])
matrix[0]

IndexError: list index out of range

In [12]:
apple_calls.where(apple_calls['strike']>343.99).dropna()

,ask,bid,contract,in-money,iv,last,last_trade,strike,strike-date,type,volume
date,,,,,,,,,,,
2020-06-09 21:09:17.973,42.75,40.90,AAPL210917C00350000,in-the-money,29.33%,41.62,2020-06-09,350.0,2021-09-17,Call,282.0
2020-06-09 21:09:17.973,38.20,36.60,AAPL210917C00360000,in-the-money,28.96%,38.50,2020-06-09,360.0,2021-09-17,Call,204.0
2020-06-09 21:09:17.973,33.95,32.15,AAPL210917C00370000,in-the-money,28.58%,33.50,2020-06-09,370.0,2021-09-17,Call,14.0
2020-06-09 21:09:17.973,29.95,28.50,AAPL210917C00380000,in-the-money,28.15%,29.35,2020-06-09,380.0,2021-09-17,Call,27.0
2020-06-09 21:09:17.973,26.50,25.25,AAPL210917C00390000,in-the-money,27.88%,25.85,2020-06-09,390.0,2021-09-17,Call,25.0
2020-06-09 21:09:17.973,23.10,21.70,AAPL210917C00400000,in-the-money,27.44%,22.40,2020-06-09,400.0,2021-09-17,Call,31.0
2020-06-09 21:09:17.973,17.95,16.80,AAPL210917C00420000,in-the-money,27.12%,17.50,2020-06-09,420.0,2021-09-17,Call,24.0
2020-06-09 21:09:17.973,15.70,14.20,AAPL210917C00430000,in-the-money,26.93%,15.60,2020-06-09,430.0,2021-09-17,Call,1.0
2020-06-09 21:09:17.973,13.70,12.70,AAPL210917C00440000,in-the-money,26.75%,13.60,2020-06-09,440.0,2021-09-17,Call,2.0
2020-06-09 21:09:17.973,11.85,11.00,AAPL210917C00450000,in-the-money,26.53%,11.67,2020-06-09,450.0,2021-09-17,Call,8.0
2020-06-09 21:09:17.973,10.20,9.20,AAPL210917C00460000,in-the-money,26.29%,9.25,2020-06-09,460.0,2021-09-17,Call,1.0
2020-06-09 21:09:17.973,8.00,6.90,AAPL210917C00480000,in-the-money,26.41%,7.85,2020-06-09,480.0,2021-09-17,Call,2.0
2020-06-09 21:09:17.973,6.70,5.60,AAPL210917C00500000,in-the-money,27.02%,6.15,2020-06-09,500.0,2021-09-17,Call,5.0

In [13]:
apple_puts.where(apple_puts['strike']<343.99).dropna()

,ask,bid,contract,in-money,iv,last,last_trade,strike,strike-date,type,volume
date,,,,,,,,,,,
2020-06-09 21:09:17.973,1.83,1.21,AAPL210917P00110000,in-the-money,54.98%,1.50,2020-06-09,110.0,2021-09-17,Put,10.0
2020-06-09 21:09:17.973,5.25,4.50,AAPL210917P00180000,in-the-money,43.51%,5.00,2020-06-09,180.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,5.55,4.50,AAPL210917P00185000,in-the-money,42.60%,5.20,2020-06-09,185.0,2021-09-17,Put,5.0
2020-06-09 21:09:17.973,7.05,6.20,AAPL210917P00200000,in-the-money,40.90%,6.05,2020-06-09,200.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,11.05,10.00,AAPL210917P00230000,in-the-money,37.87%,10.15,2020-06-09,230.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,12.65,11.60,AAPL210917P00240000,in-the-money,36.86%,12.75,2020-06-09,240.0,2021-09-17,Put,6.0
2020-06-09 21:09:17.973,14.55,13.55,AAPL210917P00250000,in-the-money,36.00%,15.00,2020-06-09,250.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,16.75,15.70,AAPL210917P00260000,in-the-money,35.26%,16.00,2020-06-09,260.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,21.95,20.80,AAPL210917P00280000,in-the-money,33.90%,21.00,2020-06-09,280.0,2021-09-17,Put,57.0
2020-06-09 21:09:17.973,28.45,27.05,AAPL210917P00300000,in-the-money,32.78%,27.67,2020-06-09,300.0,2021-09-17,Put,4.0
2020-06-09 21:09:17.973,32.15,30.20,AAPL210917P00310000,in-the-money,32.25%,31.43,2020-06-09,310.0,2021-09-17,Put,1.0
2020-06-09 21:09:17.973,36.15,34.20,AAPL210917P00320000,in-the-money,31.72%,35.42,2020-06-09,320.0,2021-09-17,Put,2.0
2020-06-09 21:09:17.973,40.60,39.00,AAPL210917P00330000,in-the-money,31.30%,39.40,2020-06-09,330.0,2021-09-17,Put,7.0
2020-06-09 21:09:17.973,45.25,43.55,AAPL210917P00340000,in-the-money,30.80%,43.44,2020-06-09,340.0,2021-09-17,Put,33.0

In [ ]:
m.update_stockprices()

Adding '[2020-01-01 00:00:00, 2020-09-12 19:34:59.612651]' data for symbol 'CLDR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:01.126654]' data for symbol 'TSLA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:02.567651]' data for symbol 'CKH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:03.779650]' data for symbol 'CLCT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:05.042650]' data for symbol 'FEYE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:06.480651]' data for symbol 'BCE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:07.958651]' data for symbol 'GOOG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:09.432046]' data for symbol 'ABBV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:10.887045]' data for symbol 'ABEO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:12.361914]' data for symbol 'BAND' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:13.803918]' data for symbol 'BBSI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:15.057915]' data for symbol 'CIT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:16.523914]' data for symbol 'CLB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:17.967917]' data for symbol 'CLIR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:19.425915]' data for symbol 'ABCB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:20.882918]' data for symbol 'AAN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:22.327917]' data for symbol 'AAPL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:23.745571]' data for symbol 'NKLA' (174 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:24.781621]' data for symbol 'ABC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:26.263947]' data for symbol 'CLDT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:27.676999]' data for symbol 'ATNM' (220 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:29.132996]' data for symbol 'NIO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:30.563001]' data for symbol 'ACGL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:32.041997]' data for symbol 'A' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:33.475026]' data for symbol 'BCBP' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:34.935007]' data for symbol 'AMZN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:36.001002]' data for symbol 'SOLO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:37.445014]' data for symbol 'CHWY' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:38.865998]' data for symbol 'MGI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:40.271000]' data for symbol 'AAL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:41.513001]' data for symbol 'AAT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:42.960002]' data for symbol 'ABT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:44.390001]' data for symbol 'BBVA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:45.826002]' data for symbol 'BC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:47.237996]' data for symbol 'CLF' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:48.710998]' data for symbol 'BBBY' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:49.929998]' data for symbol 'BBW' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:51.163999]' data for symbol 'AAON' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:52.414001]' data for symbol 'AB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:53.656001]' data for symbol 'ABMD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:54.884000]' data for symbol 'CLFD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:55.923000]' data for symbol 'CLI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:57.169999]' data for symbol 'FATE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:58.654996]' data for symbol 'ABTX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:35:59.922996]' data for symbol 'ACA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:01.153998]' data for symbol 'ABR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:02.460004]' data for symbol 'NBRV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:03.721997]' data for symbol 'ABUS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:04.990995]' data for symbol 'CIR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:06.225999]' data for symbol 'CLBS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:07.470995]' data for symbol 'VRM' (67 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:08.697998]' data for symbol 'M' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:09.933997]' data for symbol 'AMD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:11.345029]' data for symbol 'IDEX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:12.594994]' data for symbol 'MVIS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:14.049999]' data for symbol 'FB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:15.294997]' data for symbol 'IBM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:16.649999]' data for symbol 'AA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:17.907996]' data for symbol 'ABG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:19.109969]' data for symbol 'ACHC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:20.348967]' data for symbol 'BBU' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:21.802976]' data for symbol 'BBY' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:23.035972]' data for symbol 'ABM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:24.267968]' data for symbol 'CLBK' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:25.488972]' data for symbol 'FR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:26.751024]' data for symbol 'CLX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:28.185969]' data for symbol 'EBS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:29.220972]' data for symbol 'CLVS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:30.673969]' data for symbol 'CLNE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:31.926971]' data for symbol 'CLW' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:32.981970]' data for symbol 'NCLH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:34.439969]' data for symbol 'WDC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:35.695004]' data for symbol 'WDFC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:36.973035]' data for symbol 'WERN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:38.390096]' data for symbol 'WH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:39.633972]' data for symbol 'ADS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:40.853970]' data for symbol 'AEG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:42.309973]' data for symbol 'AHH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:43.538970]' data for symbol 'AIZ' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:44.965976]' data for symbol 'AL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:46.441003]' data for symbol 'ALK' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:47.935985]' data for symbol 'AMBC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:49.215969]' data for symbol 'AME' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:36:50.478969]' data for symbol 'AROC' (176 entries)
Can't add '[2020-01-01 00:00:00, 2020-09-12 19:36:51.732976]' data for symbol 'ASC
Adding '[2020-01-01 00:00:00, 2020-09-12 19:37:53.085684]' data for symbol 'AVT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:37:54.321686]' data for symbol 'AXGT' (176 entries)

Adding '[2020-01-01 00:00:00, 2020-09-12 19:37:55.769685]' data for symbol 'KSU' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:37:57.219682]' data for symbol 'KTCC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:37:58.486680]' data for symbol 'TG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:37:59.917684]' data for symbol 'WBS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:01.392682]' data for symbol 'WCC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:02.847074]' data for symbol 'ACIW' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:04.371076]' data for symbol 'AEIS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:05.813071]' data for symbol 'AGIO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:07.239073]' data for symbol 'AGTC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:08.696074]' data for symbol 'AMG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:10.170075]' data for symbol 'AMPY' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:11.590651]' data for symbol 'AMWD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:13.011645]' data for symbol 'APTS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:14.423649]' data for symbol 'ARC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:16.047649]' data for symbol 'AVEO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:17.490648]' data for symbol 'EBF' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:18.919647]' data for symbol 'KOPN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:20.375647]' data for symbol 'PINC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:21.829648]' data for symbol 'EB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:23.044651]' data for symbol 'TELL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:24.466647]' data for symbol 'WDR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:25.891646]' data for symbol 'EBSB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:27.117652]' data for symbol 'WFC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:28.363647]' data for symbol 'ED' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:29.767652]' data for symbol 'ADP' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:31.231646]' data for symbol 'HT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:32.476753]' data for symbol 'AGFS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:33.927646]' data for symbol 'KRO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:35.356650]' data for symbol 'AIA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:36.590652]' data for symbol 'PK' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:37.823651]' data for symbol 'AIG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:39.290649]' data for symbol 'SASR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:40.747649]' data for symbol 'ALSK' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:41.969245]' data for symbol 'SBSI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:43.202247]' data for symbol 'ACIU' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:44.623250]' data for symbol 'AMNB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:45.639280]' data for symbol 'AEO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:47.093283]' data for symbol 'AMSWA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:48.536244]' data for symbol 'AIV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:49.775245]' data for symbol 'ANH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:51.041277]' data for symbol 'AON' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:52.495245]' data for symbol 'ALNY' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:53.929245]' data for symbol 'APHA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:55.358813]' data for symbol 'AMCX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:56.772814]' data for symbol 'APLS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:58.202810]' data for symbol 'AMRC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:38:59.637812]' data for symbol 'APT' (220 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:00.858813]' data for symbol 'AMZA' (196 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:02.116813]' data for symbol 'AUTO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:03.359814]' data for symbol 'AVLR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:04.616808]' data for symbol 'ANDE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:05.890812]' data for symbol 'ANGI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:07.315813]' data for symbol 'ARAV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:08.559816]' data for symbol 'ARES' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:10.019820]' data for symbol 'ARKK' (196 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:11.257880]' data for symbol 'ARNA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:12.494815]' data for symbol 'ARWR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:13.524862]' data for symbol 'ATCO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:14.954813]' data for symbol 'ATHM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:16.190813]' data for symbol 'ATLC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:17.430811]' data for symbol 'ATNI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:18.820837]' data for symbol 'ATNX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:20.249814]' data for symbol 'ATSG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:21.736813]' data for symbol 'FRBK' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:23.202812]' data for symbol 'FSLR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:24.658814]' data for symbol 'KRP' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:25.906811]' data for symbol 'TEN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:27.356813]' data for symbol 'WEN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:28.793811]' data for symbol 'ABEV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:30.045810]' data for symbol 'ACLS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:31.481844]' data for symbol 'ACRE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:32.744811]' data for symbol 'ACTG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:34.008814]' data for symbol 'ACWI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:35.258812]' data for symbol 'ADMS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:36.496036]' data for symbol 'AGM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:37.523028]' data for symbol 'AKRO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:38.794031]' data for symbol 'ALGT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:40.225031]' data for symbol 'AMH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:41.663031]' data for symbol 'AMTD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:43.105030]' data for symbol 'ANF' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:44.540067]' data for symbol 'ANSS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:45.771032]' data for symbol 'APPN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:47.026057]' data for symbol 'APTV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:48.453546]' data for symbol 'ARCC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:49.924549]' data for symbol 'ASB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:51.375547]' data for symbol 'ASH' (176 entries)

Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:52.828542]' data for symbol 'ASPS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:54.284708]' data for symbol 'ATH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:55.728707]' data for symbol 'ATRS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:57.000831]' data for symbol 'AWRE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:58.247706]' data for symbol 'ECPG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:39:59.689717]' data for symbol 'HTLF' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:01.162710]' data for symbol 'HXL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:02.611703]' data for symbol 'KPTI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:03.880706]' data for symbol 'KRC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:05.335707]' data for symbol 'KURA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:06.600704]' data for symbol 'NCR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:08.039704]' data for symbol 'SBGI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:09.506703]' data for symbol 'TGNA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:10.954703]' data for symbol 'WES' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:12.378780]' data for symbol 'ACRX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:13.597705]' data for symbol 'AES' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:15.043703]' data for symbol 'AGNC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:16.500784]' data for symbol 'AGS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:17.932702]' data for symbol 'ALSN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:19.193706]' data for symbol 'ALTR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:20.458709]' data for symbol 'AM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:21.706705]' data for symbol 'ANET' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:22.927705]' data for symbol 'ASFI' (169 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:24.209726]' data for symbol 'ASHS' (196 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:25.460703]' data for symbol 'ASRV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:26.745707]' data for symbol 'ATRA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:28.183709]' data for symbol 'AVDL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:29.672702]' data for symbol 'AXGN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:31.103706]' data for symbol 'AXP' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:32.344704]' data for symbol 'KNL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:33.600705]' data for symbol 'MYRG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:34.844705]' data for symbol 'SAVA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:36.287706]' data for symbol 'TFC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:37.744705]' data for symbol 'WBT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:39.228704]' data for symbol 'WHD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:40.709706]' data for symbol 'ABB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:42.176707]' data for symbol 'ACN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:43.630706]' data for symbol 'ADMP' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:44.874705]' data for symbol 'ADTN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:46.288712]' data for symbol 'AGQ' (192 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:47.529702]' data for symbol 'AGX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:48.970706]' data for symbol 'AGYS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:50.396707]' data for symbol 'AIN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:51.620704]' data for symbol 'ALL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:53.047704]' data for symbol 'AMAT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:54.448704]' data for symbol 'ARGX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:55.863711]' data for symbol 'ASRT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:57.090707]' data for symbol 'ASUR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:58.330709]' data for symbol 'AUB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:40:59.762703]' data for symbol 'AVNS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:00.975702]' data for symbol 'AVRO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:02.423704]' data for symbol 'CLSD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:03.672703]' data for symbol 'EBIX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:04.898707]' data for symbol 'KNX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:06.136538]' data for symbol 'KOD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:07.397538]' data for symbol 'KODK' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:08.659538]' data for symbol 'KRYS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:10.091536]' data for symbol 'NBEV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:11.576665]' data for symbol 'TERP' (148 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:12.244665]' data for symbol 'WHG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:13.494669]' data for symbol 'ADM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:14.744681]' data for symbol 'ADUS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:15.954667]' data for symbol 'AERI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:17.178665]' data for symbol 'AKTS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:18.413967]' data for symbol 'APAM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:19.648963]' data for symbol 'ARVN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:20.893663]' data for symbol 'AVYA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:22.141783]' data for symbol 'AXDX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:23.556784]' data for symbol 'AXNX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:24.581158]' data for symbol 'AXTA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:25.840058]' data for symbol 'NAV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:27.294548]' data for symbol 'NAVB' (218 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:28.538792]' data for symbol 'TECH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:29.983115]' data for symbol 'AEZS' (174 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:31.216510]' data for symbol 'AGRX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:32.444273]' data for symbol 'ALLE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:33.699022]' data for symbol 'AMGN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:34.976468]' data for symbol 'AMJ' (192 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:36.391222]' data for symbol 'AMKR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:37.653584]' data for symbol 'AMLP' (196 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:38.898673]' data for symbol 'AMPE' (220 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:40.125761]' data for symbol 'AMPH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:41.338358]' data for symbol 'AN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:42.583359]' data for symbol 'AOS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:43.804466]' data for symbol 'AQMS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:45.030303]' data for symbol 'ARCB' (176 entries)

Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:46.292040]' data for symbol 'ARDX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:47.556425]' data for symbol 'ARKG' (192 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:49.046682]' data for symbol 'AT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:50.276104]' data for symbol 'ATKR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:51.514301]' data for symbol 'ATR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:52.733905]' data for symbol 'AUDC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:53.945810]' data for symbol 'AVGO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:55.156903]' data for symbol 'CLUB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:56.388005]' data for symbol 'HY' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:57.424246]' data for symbol 'HTZ' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:58.648287]' data for symbol 'HVT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:41:59.866248]' data for symbol 'KOP' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:01.343247]' data for symbol 'PJT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:02.798244]' data for symbol 'SBUX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:03.996247]' data for symbol 'SC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:05.272254]' data for symbol 'ACWV' (192 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:06.698223]' data for symbol 'ADVM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:07.920225]' data for symbol 'AFTY' (196 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:09.130226]' data for symbol 'ALG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:10.156224]' data for symbol 'ALGN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:11.392223]' data for symbol 'ANIP' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:12.677223]' data for symbol 'ANTM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:14.145225]' data for symbol 'APA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:15.386226]' data for symbol 'ATEX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:16.453225]' data for symbol 'AVID' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:17.943228]' data for symbol 'AVTR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:19.180225]' data for symbol 'ECHO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:20.638224]' data for symbol 'KNSA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:22.065222]' data for symbol 'NBIX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:23.312774]' data for symbol 'NBTB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:24.801777]' data for symbol 'PHM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:26.060776]' data for symbol 'SATS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:27.289774]' data for symbol 'TEX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:28.728770]' data for symbol 'ACES' (192 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:29.962772]' data for symbol 'ACM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:31.219775]' data for symbol 'ADRO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:32.644834]' data for symbol 'ADSK' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:33.830770]' data for symbol 'AEM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:35.260770]' data for symbol 'AG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:36.659780]' data for symbol 'AHT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:37.681319]' data for symbol 'AKBA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:38.926320]' data for symbol 'ALBO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:40.144317]' data for symbol 'ALDX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:41.368316]' data for symbol 'AMN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:42.856060]' data for symbol 'AMRS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:44.307954]' data for symbol 'AMT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:45.524552]' data for symbol 'APPF' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:46.958123]' data for symbol 'APTO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:48.226120]' data for symbol 'ARAY' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:49.496120]' data for symbol 'ARCO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:50.967492]' data for symbol 'ARD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:52.394381]' data for symbol 'ARLP' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:53.827561]' data for symbol 'ARR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:55.091085]' data for symbol 'ASML' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:56.529208]' data for symbol 'ASYS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:57.739439]' data for symbol 'ATEN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:42:59.090441]' data for symbol 'ATHX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:00.487970]' data for symbol 'ATO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:01.907973]' data for symbol 'ATVI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:03.396824]' data for symbol 'AVAV' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:04.643828]' data for symbol 'AXU' (220 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:06.119074]' data for symbol 'CLR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:07.540266]' data for symbol 'ECL' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:08.992442]' data for symbol 'HUM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:10.006185]' data for symbol 'TENB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:11.222760]' data for symbol 'TGT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:12.657008]' data for symbol 'WCN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:14.090031]' data for symbol 'ACOR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:15.291438]' data for symbol 'ADC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:16.503945]' data for symbol 'ADI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:17.936775]' data for symbol 'ADPT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:19.382256]' data for symbol 'ADSW' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:20.588080]' data for symbol 'AGG' (196 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:21.818003]' data for symbol 'AIRG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:23.036370]' data for symbol 'AKCA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:24.250363]' data for symbol 'AKR' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:25.694297]' data for symbol 'AMAG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:27.122359]' data for symbol 'AMC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:28.354317]' data for symbol 'AMED' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:29.798208]' data for symbol 'AMSF' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:31.244301]' data for symbol 'ANTE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:32.701554]' data for symbol 'APEI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:34.110574]' data for symbol 'APVO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:35.550597]' data for symbol 'ARCH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:37.005130]' data for symbol 'ARGT' (196 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:38.438170]' data for symbol 'AVA' (176 entries)

Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:39.870899]' data for symbol 'EA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:41.286187]' data for symbol 'KRG' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:42.579246]' data for symbol 'KSS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:43.783168]' data for symbol 'PKE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:45.220239]' data for symbol 'WDAY' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:46.642313]' data for symbol 'WETF' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:47.817961]' data for symbol 'WGO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:49.060190]' data for symbol 'ACWX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:50.525453]' data for symbol 'AEP' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:51.988737]' data for symbol 'AGCO' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:53.434329]' data for symbol 'ALE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:54.652838]' data for symbol 'APD' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:55.889853]' data for symbol 'APYX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:57.358880]' data for symbol 'AQST' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:58.783404]' data for symbol 'ARI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:43:59.971624]' data for symbol 'ARKW' (196 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:01.478570]' data for symbol 'ASIX' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:02.973883]' data for symbol 'ASTE' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:04.406608]' data for symbol 'ATI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:05.843936]' data for symbol 'ATRC' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:07.086553]' data for symbol 'AVB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:08.557054]' data for symbol 'AXS' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:10.021535]' data for symbol 'EAT' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:11.456347]' data for symbol 'CLNY' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:12.685991]' data for symbol 'FRTA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:13.947867]' data for symbol 'HTBI' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:15.362192]' data for symbol 'HTH' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:16.784780]' data for symbol 'HUBB' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:18.201719]' data for symbol 'HURN' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:19.429901]' data for symbol 'TEUM' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:20.676432]' data for symbol 'TEVA' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:21.892767]' data for symbol 'AAU' (220 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:23.326873]' data for symbol 'AAXJ' (176 entries)
Adding '[2020-01-01 00:00:00, 2020-09-12 19:44:24.778410]' data for symbol 'ACRS' (176 entries)

In [4]:
a = m.get_stock_data('TERP')

In [9]:
a.index[0]

'2019-12-31 14:30:00'

In [4]:
import datetime
startDate = datetime.datetime(2020, 1, 1)
endDate = datetime.datetime.now()

In [5]:
b = m.get_finnhub_prices('TERP', startDate, endDate)

In [8]:
b

AttributeError: 'Index' object has no attribute 'year'

In [21]:
b.t.dt.strftime('%m-%d-%Y')

0      12-31-2019
1      01-02-2020
2      01-03-2020
3      01-06-2020
4      01-07-2020
          ...
143    07-27-2020
144    07-28-2020
145    07-29-2020
146    07-30-2020
147    07-31-2020
Name: t, Length: 148, dtype: object