In [1]:
import scraper as s
import pandas as pd
import numpy as np
import datetime
import yfinance as yf
m = s.stockMongo()

In [2]:
op = m.get_options("AAPL")

In [3]:
op.head()

,ask,bid,contract,in-money,iv,last,last_trade,strike,strike-date,type,volume
date,,,,,,,,,,,
2020-08-02 23:39:37.026,332.30,327.95,AAPL200918C00095000,in-the-money,148.44%,284.24,2020-07-30,95.0,2020-09-18,Call,2.0
2020-08-02 23:39:37.026,279.25,277.65,AAPL200918C00100000,in-the-money,0.00%,254.30,2020-06-29,100.0,2020-09-18,Call,1.0
2020-08-02 23:39:37.026,322.50,318.00,AAPL200918C00105000,in-the-money,152.54%,264.25,2020-07-23,105.0,2020-09-18,Call,1.0
2020-08-02 23:39:37.026,317.30,312.90,AAPL200918C00110000,in-the-money,129.69%,266.25,2020-07-27,110.0,2020-09-18,Call,1.0
2020-08-02 23:39:37.026,258.90,254.10,AAPL200918C00115000,in-the-money,0.00%,255.30,2020-06-23,115.0,2020-09-18,Call,2.0

In [4]:
apl = m.get_stock_data('AAPL')
apl

,c,date,h,l,o,v
2020-01-02,75.087502,2020-01-02,75.150002,73.797501,74.059998,135647008
2020-01-03,74.357498,2020-01-03,75.144997,74.125000,74.287498,146536000
2020-01-06,74.949997,2020-01-06,74.989998,73.187500,73.447502,118579000
2020-01-07,74.597504,2020-01-07,75.224998,74.370003,74.959999,111511000
2020-01-08,75.797501,2020-01-08,76.109978,74.289001,74.290001,132364000
...,...,...,...,...,...,...
2020-09-04,120.959999,2020-09-04,123.699997,110.889999,120.070000,332607008
2020-09-08,112.820000,2020-09-08,118.959999,112.709999,113.370003,231366560
2020-09-09,117.320000,2020-09-09,119.129997,115.279999,117.190002,176940448
2020-09-10,113.489998,2020-09-10,120.220001,112.500000,120.220001,182274384
2020-09-11,112.000000,2020-09-11,115.230003,110.000000,114.570000,180860000

In [5]:
#apple = op.where(op['last_trade']==op.index.date).dropna()
apple = op
apple = apple.drop(['volume', 'iv', 'in-money', 'bid', 'ask','last_trade', 'contract'], axis=1)
apple = apple.reset_index()
apple = apple.set_index(['strike-date', 'type'])
apple['date'] = pd.to_datetime(apple['date']).dt.strftime('%m-%d-%Y')
apple['date'] = pd.to_datetime(apple['date'])
strike_pivot = apple.pivot_table(columns="strike-date", values="date", aggfunc=np.count_nonzero)
strike_cols = strike_pivot.columns
strike_cols

DatetimeIndex(['2020-08-07', '2020-08-14', '2020-08-21', '2020-08-28',
               '2020-09-04', '2020-09-11', '2020-09-18', '2020-09-25',
               '2020-10-02', '2020-10-09', '2020-10-16', '2020-10-23',
               '2020-10-30', '2020-11-06', '2020-11-13', '2020-11-20',
               '2020-11-27', '2020-12-18', '2021-01-15', '2021-06-18',
               '2021-09-17', '2022-01-21', '2022-06-17', '2022-09-16'],
              dtype='datetime64[ns]', name='strike-date', freq=None)

In [15]:
new_apple = []
apple2 = apple

for k in range(8,10):
    apple2 = apple2.reset_index()
    apple2 = apple2.set_index(['type','strike-date'])
    apple_pivot_call = apple2.loc[('Call', strike_cols[k])]
    strike_pivot = apple_pivot_call.pivot_table(columns="strike", values="date", aggfunc=np.count_nonzero)
    strike_value_cols = strike_pivot.columns
    apple_pivot_put = apple2.loc[('Put', strike_cols[k])]
    strike_pivot = apple_pivot_put.pivot_table(columns="strike", values="date", aggfunc=np.count_nonzero)
    strike_value_puts = strike_pivot.columns

    apple2 = apple2.reset_index()
    apple2 = apple2.set_index(['type', 'strike','strike-date'])
    for i in range(len(strike_value_cols)-1):
        print(i)
        for j in range(len(strike_value_puts)-1):
            aCLo = apple2.loc[('Call', strike_value_cols[i], strike_cols[k])]
            aCLo = aCLo.reset_index()
            #aCLo = aCLo.drop(['type', 'strike-date'], axis=1)
            aCLo.rename(columns = {'last':'priceCLo', 'strike': 'strikeCLo'}, inplace = True)
            aCHi = apple2.loc[('Call', strike_value_cols[i+1], strike_cols[k])]
            aCHi = aCHi.reset_index()
            #aCHi = aCHi.drop(['type', 'strike-date'], axis=1)
            aCHi.rename(columns = {'last':'priceCHi', 'strike': 'strikeCHi'}, inplace = True)
            aPLo = apple2.loc[('Put', strike_value_puts[j], strike_cols[k])]
            aPLo = aPLo.reset_index()
            #aPLo = aPLo.drop(['type', 'strike-date'], axis=1)
            aPLo.rename(columns = {'last':'pricePLo', 'strike': 'strikePLo'}, inplace = True)
            aPHi = apple2.loc[('Put', strike_value_puts[j+1], strike_cols[k])]
            aPHi = aPHi.reset_index()
            #aPHi = aPHi.drop(['type', 'strike-date'], axis=1)
            aPHi.rename(columns = {'last':'pricePHi', 'strike': 'strikePHi'}, inplace = True)

            a = pd.merge(aCLo, aCHi, on=['date', 'strike-date'])
            a = pd.merge(a, aPLo, on=['date', 'strike-date'])
            a = pd.merge(a, aPHi, on=['date', 'strike-date'])
            a = pd.merge(a, apl[['c', 'date']], on='date')
            a = a.drop(['type_x', 'type_y'], axis=1)
            a['combo'] = "C"+ str(strike_value_cols[i+1]) + "P" + str(strike_value_puts[j])

            new_apple.append(a)

print(new_apple)

c:\userdata\z003rvhr\python\yahoo_graber\grab\lib\site-packages\ipykernel_launcher.py:7: PerformanceWarning: indexing past lexsort depth may impact performance.
  import sys
c:\userdata\z003rvhr\python\yahoo_graber\grab\lib\site-packages\ipykernel_launcher.py:10: PerformanceWarning: indexing past lexsort depth may impact performance.
  # Remove the CWD from sys.path while we load stuff.

0

c:\userdata\z003rvhr\python\yahoo_graber\grab\lib\site-packages\ipykernel_launcher.py:19: PerformanceWarning: indexing past lexsort depth may impact performance.
c:\userdata\z003rvhr\python\yahoo_graber\grab\lib\site-packages\ipykernel_launcher.py:23: PerformanceWarning: indexing past lexsort depth may impact performance.
c:\userdata\z003rvhr\python\yahoo_graber\grab\lib\site-packages\ipykernel_launcher.py:27: PerformanceWarning: indexing past lexsort depth may impact performance.
c:\userdata\z003rvhr\python\yahoo_graber\grab\lib\site-packages\ipykernel_launcher.py:31: PerformanceWarning: indexing past lexsort depth may impact performance.

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [16]:
new_apple = pd.concat(new_apple)

In [21]:
new_apple = new_apple.reset_index()
#new_apple.loc['C100.00P110.00']

strike_pivot = new_apple.pivot_table(columns="combo", values="date", aggfunc=np.count_nonzero)
strike_value_cols = strike_pivot.columns
strike_value_cols
    
#a = new_apple.where(new_apple['strikeCLo']>=new_apple['c']).dropna()
#a = a.where(a['strikePHi']<=a['c']).dropna()

Index(['C100.0P100.0', 'C100.0P101.25', 'C100.0P102.5', 'C100.0P103.75',
       'C100.0P105.0', 'C100.0P106.25', 'C100.0P107.5', 'C100.0P108.75',
       'C100.0P110.0', 'C100.0P111.25',
       ...
       'C98.75P87.5', 'C98.75P88.75', 'C98.75P90.0', 'C98.75P91.25',
       'C98.75P92.5', 'C98.75P93.75', 'C98.75P95.0', 'C98.75P96.25',
       'C98.75P97.5', 'C98.75P98.75'],
      dtype='object', name='combo', length=20093)

In [29]:
ap = op[op['volume']>100]
ap = ap[ap['strike-date']=='2020-10-16']
ap = ap[ap['strike'] == 460]
ap = ap[ap['type'] =="Put"]
ap['last']

date
2020-08-06 20:02:24.073    30.40
2020-08-13 20:01:58.831    27.40
2020-08-14 20:02:01.695    28.60
2020-08-15 20:02:02.929    27.72
2020-08-16 20:01:56.092    27.72
2020-08-17 20:01:58.482    26.60
2020-08-18 20:01:48.908    24.73
2020-08-20 20:01:45.029    20.00
2020-08-21 20:01:46.919    16.58
2020-08-22 20:01:34.780    16.00
2020-08-23 20:01:39.194    16.00
2020-08-25 20:02:11.178    15.70
2020-08-26 20:02:03.971    17.05
2020-08-27 20:07:59.149    19.00
2020-08-28 20:07:51.047    16.90
Name: last, dtype: float64

In [12]:
new_apple = []
apple2 = apple

apple2 = apple2.reset_index()
apple2 = apple2.set_index(['type','strike-date'])
apple_pivot_call = apple2.loc[('Call', strike_cols[8])]
strike_pivot = apple_pivot_call.pivot_table(columns="strike", values="date", aggfunc=np.count_nonzero)
strike_value_cols = strike_pivot.columns
apple_pivot_put = apple2.loc[('Put', strike_cols[8])]
strike_pivot = apple_pivot_put.pivot_table(columns="strike", values="date", aggfunc=np.count_nonzero)
strike_value_puts = strike_pivot.columns
    
apple2 = apple2.reset_index()
apple2 = apple2.set_index(['type', 'strike','strike-date'])

apple2.loc[('Call', strike_value_puts[4], strike_cols[8])]

c:\userdata\z003rvhr\python\yahoo_graber\grab\lib\site-packages\ipykernel_launcher.py:6: PerformanceWarning: indexing past lexsort depth may impact performance.

c:\userdata\z003rvhr\python\yahoo_graber\grab\lib\site-packages\ipykernel_launcher.py:9: PerformanceWarning: indexing past lexsort depth may impact performance.
  if __name__ == '__main__':
c:\userdata\z003rvhr\python\yahoo_graber\grab\lib\site-packages\ipykernel_launcher.py:16: PerformanceWarning: indexing past lexsort depth may impact performance.
  app.launch_new_instance()

                              date  last
type strike strike-date
Call 67.5   2020-10-02  2020-09-02  63.5
            2020-10-02  2020-09-03  54.8
            2020-10-02  2020-09-04  54.8
            2020-10-02  2020-09-05  54.8
            2020-10-02  2020-09-06  54.8
            2020-10-02  2020-09-07  54.8
            2020-10-02  2020-09-08  54.8
            2020-10-02  2020-09-09  54.8
            2020-10-02  2020-09-10  54.8
            2020-10-02  2020-09-11  54.8
            2020-10-02  2020-09-12  54.8
            2020-10-02  2020-09-13  54.8
            2020-10-02  2020-09-14  54.8
            2020-10-02  2020-09-15  54.8
            2020-10-02  2020-09-16  54.8
            2020-10-02  2020-09-17  54.8
            2020-10-02  2020-09-18  54.8
            2020-10-02  2020-09-19  54.8
            2020-10-02  2020-09-20  54.8
            2020-10-02  2020-09-21  54.8

In [12]:
range(8,10)

range(8, 10)

In [2]:
aapl = yf.Ticker("AAPL")

In [5]:
aapl.options[0]

'2020-10-23'

In [6]:
opt = aapl.option_chain(aapl.options[0])

In [10]:
opt.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL201023C00055000,2020-10-16 19:05:38,55.0,64.90,63.85,64.90,0.150002,0.231663,10,44,3.164065,True,REGULAR,USD
1,AAPL201023C00060000,2020-10-15 17:31:44,60.0,59.65,58.85,59.90,0.000000,0.000000,1,53,2.843753,True,REGULAR,USD
2,AAPL201023C00065000,2020-10-16 14:55:11,65.0,55.70,53.85,54.90,0.980000,1.790935,3,15,2.546879,True,REGULAR,USD
3,AAPL201023C00070000,2020-10-15 16:49:16,70.0,49.70,48.85,49.90,0.000000,0.000000,1,111,2.271489,True,REGULAR,USD
4,AAPL201023C00075000,2020-10-16 19:33:27,75.0,44.10,43.85,44.35,-1.780003,-3.879692,26,43,1.593752,True,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,AAPL201023C00155000,2020-10-16 19:54:34,155.0,0.01,0.01,0.02,-0.010000,-50.000000,757,2914,0.765627,False,REGULAR,USD
62,AAPL201023C00160000,2020-10-16 19:31:42,160.0,0.02,0.01,0.02,0.000000,0.000000,47,2948,0.843752,False,REGULAR,USD
63,AAPL201023C00165000,2020-10-16 19:05:14,165.0,0.02,0.00,0.00,0.010000,100.000000,601,3669,0.500005,False,REGULAR,USD
64,AAPL201023C00170000,2020-10-16 19:59:12,170.0,0.17,0.00,0.01,0.160000,1600.000000,524,2923,0.906251,False,REGULAR,USD
65,AAPL201023C00175000,2020-10-16 14:44:55,175.0,0.01,0.00,0.00,0.000000,0.000000,64,4668,0.500005,False,REGULAR,USD